development:
  adapter: postgresql
  encoding: utf8
  database: kinoman_development
  pool: 5
  username: kinoman
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: kinoman_test
  pool: 5
  username: kinoman
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: kinoman_production
  pool: 5
  username: kinoman
  password:
